services:
  mysql:
    image: mysql:8.0
    volumes:
      - skillshare-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "skillshare"

  app:
    image: node:18-alpine
    command: sh -c "npm i && npm run start:dev"
    ports:
      - 3000:3000
    working_dir: /skillshare
    volumes:
      - ./:/skillshare
      - /node_modules:/skillshare/node_modules
    environment:
      DB_PORT: "3306"
      DB_HOST: "mysql"
      DB_USERNAME: "root"
      DB_PASSWORD: "123456"
      DB_NAME: "skillshare"

volumes:
  skillshare-data: