services:
  app:
    image: node:18-alpine
    command: sh -c "npm i && npm run start:dev"
    ports:
      - 127.0.0.1:3000:3000
    working_dir: /src
    volumes:
      - ./:/src
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: skillshare

  database:
    image: mysql:8.0
    volumes:
      - skillshare-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: skilshare

volumes:
  skillshare-data: